name: .NET Core Build

on: [push]

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.402"
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.607"
      - name: build package
        run: dotnet run -p ./build/nukebuild.csproj -- --Configuration Release --Target Pack
      - name: collect artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Unofficial.Npgsql.DiagnosticSource.nupkg
          path: dist/Release
      - name: nuget package push
        run: dotnet run -p ./build/nukebuild.csproj -- --Configuration Release --Target GithubPush --GithubUsername itn3000 --GithubToken ${{secrets.GITHUB_TOKEN}} --GithubPackageUrl "https://nuget.pkg.github.com/itn3000/index.json"
